//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainsWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndirectTrains
    {
        public int Id1 { get; set; }
        public int Id2 { get; set; }
        public System.DateTime DepTime1 { get; set; }
        public string Origin1 { get; set; }
        public System.DateTime ArrTime1 { get; set; }
        public string Dest1 { get; set; }
        public System.DateTime DepTime2 { get; set; }
        public string Dest2 { get; set; }
        public System.DateTime ArrTime2 { get; set; }
        public Nullable<int> Cost { get; set; }
    }
}
