//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainsWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketInfo
    {
        public int TicketID { get; set; }
        public int ID { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public System.DateTime DepartTime { get; set; }
        public System.DateTime ArriveTime { get; set; }
        public int MaxCapacity { get; set; }
        public int TicketCost { get; set; }
        public string UserTelNum { get; set; }
    }
}
